### ISSUE TITLE
Not working on 1.14.2

### ISSUE THREAD

**Issue by iusearch** [Nort721/SimpleFlyPlugin#1]
I downloaded the 1.17 version and put it into plugin folder. It gives this error:
```
[04:50:46] [Server thread/WARN]: [SimpleFlyPlugin] Task #5 for SimpleFlyPlugin v1.17 generated an exception
--
java.lang.IllegalArgumentException: No enum constant org.bukkit.Effect.CLOUD
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
at org.bukkit.Effect.valueOf(Effect.java:13) ~[patched_1.14.2.jar:git-Paper-66]
at me.Nort721.Fly.SimpleFlyPlugin$1.run(SimpleFlyPlugin.java:161) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-66]
at  org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)  ~[patched_1.14.2.jar:git-Paper-66]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114) ~[patched_1.14.2.jar:git-Paper-66]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

Would you like to push your latest 1.17 source so I can modify it to justify 1.14.2?

**Comment by 0xntpower** [comment]
I know that this is super old, but know that you can just disable the cloud effect to make is error be gone, I don't really support the plugin anymore but I may release a full recode for it soon
