### ISSUE TITLE
Working but issues in logs

### ISSUE THREAD

**Issue by Ectalite** [Nort721/SimpleFlyPlugin#2]
Hello, 
You made an awesome simple plugin and thanks for that, but I get that error in the logs :
```
[17:46:05] [Server thread/WARN]: [SimpleFlyPlugin] Task #1592 for SimpleFlyPlugin v1.17 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Effect.CLOUD
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_192]
	at org.bukkit.Effect.valueOf(Effect.java:13) ~[patched_1.14.4.jar:git-Paper-175]
	at me.Nort721.Fly.SimpleFlyPlugin$1.run(SimpleFlyPlugin.java:161) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```
Is there a way to fix it ?

**Comment by 0xntpower** [comment]
disable the fly cloud effect

**Comment by velnias75** [comment]
> disable the fly cloud effect

You also may set an `api-version` in `plugin.yml`
